name: "Run integration tests"
description: "Runs integration tests"
runs:
  using: "composite"
  steps:
    - name: install yarn
      run: npm install -g yarn
      shell: bash

    - name: yarn install
      run: |
        yarn install
      shell: bash

    - name: "yarn run test:int"
      run: |
        yarn run test:int
      shell: bash