name: dev

on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  ENV: dev
  AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
  NPM_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}
  ENCOMPASS_API_BASE_URL: https://elliemae-api-proxy.devrm.io
  ENCOMPASS_CLIENT_ID: ${{ secrets.DEV_ENCOMPASS_CLIENT_ID }}
  ENCOMPASS_CLIENT_SECRET: ${{ secrets.DEV_ENCOMPASS_CLIENT_SECRET }}
  ENCOMPASS_SMART_CLIENT_USER: ${{ secrets.DEV_ENCOMPASS_SMART_CLIENT_USER }}
  ENCOMPASS_SMART_CLIENT_PASSWORD: ${{ secrets.DEV_ENCOMPASS_SMART_CLIENT_PASSWORD }}
  ENCOMPASS_API_KEY: ${{ secrets.DEV_ENCOMPASS_API_KEY }}
  ENCOMPASS_INSTANCE: ${{ secrets.DEV_ENCOMPASS_INSTANCE }}
  CREDIT_PLUS_API_BASE_URL: https://creditplus-api-proxy.devrm.io
  CREDIT_PLUS_API_KEY: ${{ secrets.DEV_CREDIT_PLUS_API_KEY }}
  CREDIT_PLUS_API_USERNAME: ${{ secrets.DEV_CREDIT_PLUS_API_USERNAME }}
  CREDIT_PLUS_API_PASSWORD: ${{ secrets.DEV_CREDIT_PLUS_API_PASSWORD }}
  TABLE_NAME: dev-cp-efolder-upload

jobs:
  build:
    name: "Build"
    
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}

      - name: "run unit tests"
        uses: ./.github/actions/unit-test

  test:
    needs: [ build ]
    name: "Test"
    
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}

      - name: "run integration tests"
        uses: ./.github/actions/int-test

  deploy:
    needs: [ test ]
    name: "Deploy to dev"

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: Fooji/create-aws-profile-action@v1
        with:
          profile: devAccount
          region: us-east-2
          key: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          secret: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

      - name: "deploy"
        uses: ./.github/actions/deploy
